# Generated by Django 5.2.7 on 2025-10-27 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_client_clientimage_clientcontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry', models.DateTimeField(help_text='Date and time when the subscription expires', verbose_name='expiry date')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the subscription was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the subscription was last updated', verbose_name='updated at')),
                ('user', models.OneToOneField(help_text='The user this subscription belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
                'ordering': ['-expiry'],
            },
        ),
    ]
