# Generated by Django 5.2.7 on 2025-10-28 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_subscription_options_subscription_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
    ]
