# Generated by Django 5.2.4 on 2025-10-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('status_change', 'Status Change'), ('comment', 'Comment'), ('evidence_added', 'Evidence Added'), ('assignment_change', 'Assignment Change'), ('resolution', 'Resolution')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(help_text='Unique incident identifier', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Brief description of the incident', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the incident')),
                ('incident_type', models.CharField(choices=[('fraud', 'Fraud Attempt'), ('unauthorized_access', 'Unauthorized Access'), ('property_damage', 'Property Damage'), ('suspicious_activity', 'Suspicious Activity'), ('verification_failure', 'Verification Failure'), ('payment_fraud', 'Payment Fraud'), ('identity_theft', 'Identity Theft'), ('harassment', 'Harassment'), ('noise_complaint', 'Noise Complaint'), ('other', 'Other')], help_text='Type of security incident', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Severity level of the incident', max_length=10)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('escalated', 'Escalated')], default='reported', help_text='Current status of the incident', max_length=15)),
                ('guest_name', models.CharField(blank=True, help_text='Name of guest involved in incident', max_length=100, null=True)),
                ('guest_email', models.EmailField(blank=True, help_text='Email of guest involved in incident', max_length=254, null=True)),
                ('guest_phone', models.CharField(blank=True, help_text='Phone number of guest involved', max_length=20, null=True)),
                ('incident_date', models.DateTimeField(help_text='Date and time when the incident occurred')),
                ('reported_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when incident was reported')),
                ('resolved_date', models.DateTimeField(blank=True, help_text='Date and time when incident was resolved', null=True)),
                ('location_description', models.TextField(blank=True, help_text='Specific location within property where incident occurred', null=True)),
                ('evidence_files', models.JSONField(blank=True, default=list, help_text='List of file paths to evidence (photos, videos, documents)')),
                ('estimated_damage_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost of damages', max_digits=10, null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about how the incident was resolved', null=True)),
                ('police_report_number', models.CharField(blank=True, help_text='Police report number if applicable', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Security Incident',
                'verbose_name_plural': 'Security Incidents',
                'ordering': ['-reported_date'],
            },
        ),
    ]
