# Generated by Django 5.2.4 on 2025-10-25 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='securityincident',
            name='reported_by',
            field=models.ForeignKey(help_text='User who reported the incident', on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentupdate',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='home.securityincident'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['incident_type', 'status'], name='home_securi_inciden_d2a555_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['severity', 'reported_date'], name='home_securi_severit_9c977d_idx'),
        ),
        migrations.AddIndex(
            model_name='securityincident',
            index=models.Index(fields=['reported_by', 'incident_date'], name='home_securi_reporte_3a9d7c_idx'),
        ),
    ]
