# Generated by Django 5.2.7 on 2025-10-26 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_initial'),
        ('users', '0002_client_clientimage_clientcontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityincident',
            name='guest_email',
        ),
        migrations.RemoveField(
            model_name='securityincident',
            name='guest_name',
        ),
        migrations.RemoveField(
            model_name='securityincident',
            name='guest_phone',
        ),
        migrations.AddField(
            model_name='securityincident',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.client'),
        ),
    ]
