# Generated by Django 5.2.7 on 2025-10-27 09:33

import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_securityincident_guest_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload image or video evidence', upload_to=home.models.evidence_upload_path)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('other', 'Other')], help_text='Type of evidence file', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Brief description of the evidence', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('mime_type', models.CharField(blank=True, help_text='MIME type of the file', max_length=100)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='home.securityincident')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the evidence', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Evidence',
                'verbose_name_plural': 'Incident Evidence',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
