# Generated by Django 5.2.7 on 2025-10-27 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_incidentevidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='home.securityincident')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incident Comment',
                'verbose_name_plural': 'Incident Comments',
                'ordering': ['-created_at'],
            },
        ),
    ]
