# Generated by Django 5.2.7 on 2025-10-27 20:37

import django.core.validators
import django.db.models.deletion
import home.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplainerVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(help_text='Upload a video explanation of the incident', upload_to=home.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'avi'])])),
                ('title', models.CharField(default='Incident Explanation', help_text='Title for the explainer video', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the video content', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident', models.OneToOneField(help_text='The incident this video explains', on_delete=django.db.models.deletion.CASCADE, related_name='explainer_video', to='home.securityincident')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded the video', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Explainer Video',
                'verbose_name_plural': 'Explainer Videos',
                'ordering': ['-created_at'],
            },
        ),
    ]
